name: GitHub Projects Display

on:
  push:
    branches:
      - main

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Display GitHub Projects
        uses: kaustubhgupta/readme-projects-display@v1
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          file_name: 'README.md'
          max_repo_description: 50
          allow_forks: true
          project_sort_by: 'stars'
